variable project_id {}
variable zone {}
variable region {}
variable machine_type {}
variable boot_disk_images {}
variable public_key_path {}
variable private_key_path {}
variable remote_user {}
variable remote_dir {}
variable zsh {}
variable terraform {}
variable terraform_version {}
variable ansible {}
variable kubectl {}
variable jq {}
variable helm {}
variable sops {}
variable sops_version {}
variable k9s {}